name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build project
        run: |
          # add secrets to process.env
            echo "NEXT_PUBLIC_VERCEL_URL=$VERCEL_URL" >> .env.local
          yarn install
          yarn build

  lint:
    runs-on: ubuntu-latest

    needs: install_and_build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint project
        run: yarn lint

  run_tests:
    runs-on: ubuntu-latest

    needs: lint
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests with Playwright
        run: yarn test

  deploy:
    runs-on: ubuntu-latest

    needs: run_tests
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        run:  echo "Deploying to Vercel"
