name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: production
    env:
      CI: true
      HUBSPOT_LEAD_FORM_ID: ${{ secrets.HUBSPOT_LEAD_FORM_ID }}
      HUBSPOT_API_URL: ${{ secrets.HUBSPOT_API_URL }}
      HUBSPOT_PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
      DATOCMS_READONLY_TOKEN: ${{ secrets.DATOCMS_READONLY_TOKEN }}
      NEXT_DATOCMS_API_TOKEN: ${{ secrets.NEXT_DATOCMS_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

        with:
          node-version: '20'
          cache: 'yarn'

      - name: copy secrets from github secret to .env file
        run: |
          echo $HUBSPOT_LEAD_FORM_ID
          echo HUBSPOT_LEAD_FORM_ID=$HUBSPOT_LEAD_FORM_ID >> .env
          echo HUBSPOT_API_URL=$HUBSPOT_API_URL >> .env
          echo HUBSPOT_PORTAL_ID=$HUBSPOT_PORTAL_ID >> .env
          echo DATOCMS_READONLY_TOKEN=$DATOCMS_READONLY_TOKEN >> .env
          echo NEXT_DATOCMS_API_TOKEN=$NEXT_DATOCMS_API_TOKEN >> .env
          

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

  tests:
    runs-on: ubuntu-latest

    needs: prepare
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest

    needs: tests
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

        with:
          node-version: '20'
          cache: 'yarn'

      - name: Deploy to Vercel
        run: npx vercel --prod

